public enum eAttackPattern
{
    NO_ATTACK = 10,
    ATTACK_WITH_EIGHT = 21,
    ATTACK_PLAYER_DIRECTION_1 = 31,
    ATTACK_PLAYER_DIRECTION_2 = 32,
    ATTACK_HOMING = 41,
    ATTACK_WITH_EIGHT_AND_PLAYER_DIRECTION = 51,
}