//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.2
//     from Assets/InputActions/ControlActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlActions"",
    ""maps"": [
        {
            ""name"": ""Title"",
            ""id"": ""ec4a50a3-525a-4c08-a7bc-1763757e26a7"",
            ""actions"": [
                {
                    ""name"": ""EnterProcess"",
                    ""type"": ""Button"",
                    ""id"": ""adfa5bcd-8368-4458-a4de-d0e2a639dab2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectDown"",
                    ""type"": ""Button"",
                    ""id"": ""a3b43935-ac8e-4309-b96e-628f3eacee9c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectUp"",
                    ""type"": ""Button"",
                    ""id"": ""1202fb5b-093f-41a6-9e55-5d2f252f44d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ad67c31f-194e-4b11-a64c-f99f0cdba4fa"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e05fd252-2e97-45a9-a715-de3955dae1a5"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a7433fd-792b-403a-80e4-b4f1c3f1ecab"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""34196164-88ad-4ffc-846d-0916971c5999"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef11ccfa-36fa-4b54-9398-3b4ffac39ea5"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""70eae772-8ffb-45fa-899f-f57ea89d83f1"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""51fe114c-672d-479e-a2f9-b69410cac3c2"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnterProcess"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e25ee4b-26ca-4342-adbd-9f1f0712d650"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnterProcess"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15b5529d-c62c-421f-8651-3684c94bf533"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnterProcess"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8ecd0b57-fbae-442a-96f0-e60a06f15846"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnterProcess"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Play"",
            ""id"": ""9992f1d9-35bc-4552-9a1d-d8dbb296dee5"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""ac197ff4-b884-4c0a-9749-e6462bc1feda"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""274d78fc-d69b-4c21-8349-503c1b9fa0ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""3a997fb2-95d6-4715-a832-0a8aa427e133"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangeWeaponToLeft"",
                    ""type"": ""Button"",
                    ""id"": ""e80a4fb2-5efd-448c-b402-1a4e9ce8f276"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeWeaponToRight"",
                    ""type"": ""Button"",
                    ""id"": ""b507a8ad-7df2-4997-b9d5-61f468445de5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AdjustCameraDistance"",
                    ""type"": ""Button"",
                    ""id"": ""59d8f5bd-28e5-4bec-acbf-94ff1a7713c3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Resurrection"",
                    ""type"": ""Button"",
                    ""id"": ""a1aed4fe-0771-4775-aa14-c209c820ba35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HighSpeedMove"",
                    ""type"": ""Button"",
                    ""id"": ""78ce297b-685c-4b03-8247-83c8e2461fb0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToPause"",
                    ""type"": ""Button"",
                    ""id"": ""f460dd48-f6ad-4207-a9cb-812f83ec68ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FullHeal"",
                    ""type"": ""Button"",
                    ""id"": ""6c51d834-3d8b-4745-b7e8-e7f87669bf9e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FullFood"",
                    ""type"": ""Button"",
                    ""id"": ""358e5ba8-1dc5-4f3f-b85a-b8a6d1e08349"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FullWater"",
                    ""type"": ""Button"",
                    ""id"": ""80108444-bbc0-42fc-9ad8-4138b4f3e2c4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenDebugMode"",
                    ""type"": ""Button"",
                    ""id"": ""6a85e2a1-115e-4bd1-974c-144175fafbf7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3accc23f-d890-409a-aa9f-34488ba44a9b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""bce08562-8c45-4e06-b861-603316acd140"",
                    ""path"": ""Dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""890b3903-029f-4d45-9e40-e60cdd441858"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""27b3e3da-de25-42ee-bd48-f22b7e44761e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""481ccb40-9e16-46c9-9247-17a418de1a9e"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""248bda07-9685-4c69-9ca1-6ef791784323"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b9dace67-e02f-499a-a42f-29bbd1a80144"",
                    ""path"": ""<DualShockGamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8d41ac1-beaf-46ed-85fe-4bb5e4f83a35"",
                    ""path"": ""<DualShockGamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""760b068e-2453-4c25-ad6d-cc33714db3d2"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7322d0b2-3786-4b74-afeb-d810ecb64120"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9b5eaf32-9a6b-4b11-b5c1-f5595fc828af"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc669abb-f2cd-4f83-ac5e-24aecd7d8d84"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb417392-a313-4d60-a2b9-fc13f66aaa57"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f5fc295-944a-4b57-afc5-214ec1ea5267"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""117d61b0-bcd6-4f16-8c7b-a71c50a8bd34"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ChangeWeaponToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e6b0bec-163f-4413-bad1-01ea3660ad8a"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ChangeWeaponToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5e1c7bad-ec23-4e41-965f-9904d76c5f81"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ChangeWeaponToLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc46d239-cafb-4715-a1ac-d9cdaa00edb1"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ChangeWeaponToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1108e67e-8453-493d-9069-e4e6ca25696b"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeaponToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a1b0baae-92d1-4138-8de7-856996bcf322"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeWeaponToRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8601ee8-bcb3-48c5-8d25-a0a68ce06ef8"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""AdjustCameraDistance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cd506478-52ff-4b73-ae4c-ba17ee266a06"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AdjustCameraDistance"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bea38bb3-9610-4999-ae15-61001e60f5b9"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Resurrection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbbc6efe-62f8-4c7b-a724-74aab81be02b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HighSpeedMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50be43e7-c544-4af3-a010-92170ef62181"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""HighSpeedMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dac234a5-30d5-4b40-9ecf-b7956fedc800"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ToPause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2e893d79-0b35-4f17-9ef9-8d50eba70f40"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ToPause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c824279d-22d6-4f74-a9d5-7a74df6a9b05"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FullHeal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f553275a-ffd9-4fb0-8120-9581dbecd765"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FullFood"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ebbf2cb-9fff-4baf-895f-5a268bb61d7d"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FullWater"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05f4d7af-eec5-491f-b1e9-fbb98e26a4e5"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenDebugMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Pause"",
            ""id"": ""3cdd13ae-d421-4477-a790-940fbf53b82c"",
            ""actions"": [
                {
                    ""name"": ""SelectLeft"",
                    ""type"": ""Button"",
                    ""id"": ""6f5043c5-8e09-45cc-8941-2ac22d4242aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectRight"",
                    ""type"": ""Button"",
                    ""id"": ""27a4f116-b685-4f87-be23-badac2c889f4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Enter"",
                    ""type"": ""Button"",
                    ""id"": ""eadadfb7-b867-4502-8584-7cdf69d3c240"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e061ca19-4a99-483d-9c9b-4e15c6983781"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SelectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a6c1d7c-fde3-4762-86e3-bc022362b5b3"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19bd69e9-47be-4c99-8b3a-4fa16b728662"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a2ae7ba-8b07-42a9-b375-ca5b0196de59"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SelectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d927a0b6-e359-49b8-abcc-274358474cc3"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""69ab2dec-a803-4a4d-b56c-6e286bba6d3a"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Enter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8fcf8ec5-7128-440f-9ca4-9ac1082eac1f"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""48767579-d389-449d-a70f-108d5cc2376d"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Result"",
            ""id"": ""5f20e910-6aef-41c5-b7b7-2fe3777380b9"",
            ""actions"": [
                {
                    ""name"": ""BackToTitle"",
                    ""type"": ""Button"",
                    ""id"": ""b2f8dbd0-6d5a-48ff-b763-134abbfb91ce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectLeftOnLevelUp"",
                    ""type"": ""Button"",
                    ""id"": ""cd2bb06f-309c-48d4-bd49-76590e35752b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectRightOnLevelUp"",
                    ""type"": ""Button"",
                    ""id"": ""5db71bf2-d43f-42fb-8f20-dab94565e34b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectUpOnEndLevelUp"",
                    ""type"": ""Button"",
                    ""id"": ""dc9a0689-8ad5-4978-974b-34daa980854d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectDownOnEndLevelUp"",
                    ""type"": ""Button"",
                    ""id"": ""41430055-c10c-478b-96e1-00bbdd9439c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ebef2b81-8a66-4b5b-8b06-4ee63bcf8e98"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackToTitle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba86533d-bfcd-406f-81f3-1bc9b305d895"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackToTitle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5dc5fdf-c60c-4daa-9ffc-7b0f7d87ba2d"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectLeftOnLevelUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42a26536-a087-4699-9927-2a99da26713f"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectRightOnLevelUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba9956dc-ee29-4185-81ca-9b5187416e3a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectUpOnEndLevelUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""487af185-d6dc-49b7-b58a-7e870ea89a08"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectDownOnEndLevelUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debug"",
            ""id"": ""4df3661d-e4b6-4fd2-96c2-256cebd08f2e"",
            ""actions"": [
                {
                    ""name"": ""DebugMode_Submit"",
                    ""type"": ""Button"",
                    ""id"": ""35d56a1f-ad0e-4ca4-8197-9f1e97e0df0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugMode_Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""91e08df0-632e-47b5-a934-04f8c58ffadf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugMode_Down"",
                    ""type"": ""Button"",
                    ""id"": ""3703620d-ef8e-41c3-9805-5bc59c096c2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugMode_Up"",
                    ""type"": ""Button"",
                    ""id"": ""58d4b8ba-9f55-41ce-8ac7-f870f49e78b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugMode_Right"",
                    ""type"": ""Button"",
                    ""id"": ""77f8670e-86bd-4e12-ad68-b7d052e96913"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugMode_Left"",
                    ""type"": ""Button"",
                    ""id"": ""2270b44b-c896-4c91-8906-2644dd32b544"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.2)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b6edfc8b-3505-49da-8afb-0eeef744fcf5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMode_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9833c7db-5cc5-4277-b4d9-d0e2a42d3717"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMode_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cccdcdb-3355-457e-aae8-5a37353896e4"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMode_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f69f8fcb-c515-411c-943c-e52939ae9386"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMode_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5b86b80-7b46-4cfb-9e44-014cbc052b8b"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMode_Up"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b209627-52b5-4840-bf40-3cee0c505ca9"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMode_Down"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32e2b087-6c05-4e3c-92e5-9cff6849bad9"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMode_Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5afab135-0b89-4443-857f-cb6b7282d766"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMode_Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""616b8351-2d21-42a7-beb6-a3950fc56ee4"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMode_Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a23ae99b-03a9-4aeb-8319-1b135cdfc071"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugMode_Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""DebugTitle"",
            ""id"": ""274cde53-2835-4bf3-ab28-4e6650b2332c"",
            ""actions"": [
                {
                    ""name"": ""Stage1"",
                    ""type"": ""Button"",
                    ""id"": ""bba83afa-d68b-4e2f-a5b0-11707c43979e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stage2"",
                    ""type"": ""Button"",
                    ""id"": ""fbabe1e3-8da9-49d7-9b91-08bdf58a4fd9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stage3"",
                    ""type"": ""Button"",
                    ""id"": ""89b6e82b-f969-4fe0-8e04-a6e3ee35567a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stage4"",
                    ""type"": ""Button"",
                    ""id"": ""7357b69e-b8dd-43e5-8e31-e1d7ad3474d4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stage5"",
                    ""type"": ""Button"",
                    ""id"": ""1c255abf-34bc-4609-9883-7222dc4a862f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stage6"",
                    ""type"": ""Button"",
                    ""id"": ""eb400cc6-8e33-4ba0-851c-d10e9330b655"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stage7"",
                    ""type"": ""Button"",
                    ""id"": ""399ad824-5f8d-4ca0-b06e-45d5d8a7f91b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stage8"",
                    ""type"": ""Button"",
                    ""id"": ""847c6321-08ab-4fce-8edf-abc1b904f78d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stage9"",
                    ""type"": ""Button"",
                    ""id"": ""9c6e0185-6c99-45e2-ad38-e67dd16b8b0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stage10"",
                    ""type"": ""Button"",
                    ""id"": ""3c9daee3-7d8f-463b-a0b6-45832f0df9d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f826f65e-815e-49be-a935-dd1628126fd3"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stage1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9289848-3237-4930-b799-f74cf8f21da8"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stage2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9c61aef-de00-40d1-98d9-12257d9a5730"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stage3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cddbc535-1bff-40b8-a6e9-ce2c6dbe0d01"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stage4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7eb5dbc-ec75-4ae9-a239-71f81512696b"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stage5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8534807-1aef-4d93-bcd5-4b96eb0a0968"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stage6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c53a5db5-2a84-4a74-a567-75a6a9e14ad3"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stage7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b17280ed-5bfc-44b7-9989-8ac6fe2aab89"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stage8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99d59153-5a5e-4ea0-a708-4456dbdaaef2"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stage9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""976a8804-b895-4e38-bd0a-f72472c25c2b"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stage10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Title
        m_Title = asset.FindActionMap("Title", throwIfNotFound: true);
        m_Title_EnterProcess = m_Title.FindAction("EnterProcess", throwIfNotFound: true);
        m_Title_SelectDown = m_Title.FindAction("SelectDown", throwIfNotFound: true);
        m_Title_SelectUp = m_Title.FindAction("SelectUp", throwIfNotFound: true);
        // Play
        m_Play = asset.FindActionMap("Play", throwIfNotFound: true);
        m_Play_Move = m_Play.FindAction("Move", throwIfNotFound: true);
        m_Play_Attack = m_Play.FindAction("Attack", throwIfNotFound: true);
        m_Play_Dash = m_Play.FindAction("Dash", throwIfNotFound: true);
        m_Play_ChangeWeaponToLeft = m_Play.FindAction("ChangeWeaponToLeft", throwIfNotFound: true);
        m_Play_ChangeWeaponToRight = m_Play.FindAction("ChangeWeaponToRight", throwIfNotFound: true);
        m_Play_AdjustCameraDistance = m_Play.FindAction("AdjustCameraDistance", throwIfNotFound: true);
        m_Play_Resurrection = m_Play.FindAction("Resurrection", throwIfNotFound: true);
        m_Play_HighSpeedMove = m_Play.FindAction("HighSpeedMove", throwIfNotFound: true);
        m_Play_ToPause = m_Play.FindAction("ToPause", throwIfNotFound: true);
        m_Play_FullHeal = m_Play.FindAction("FullHeal", throwIfNotFound: true);
        m_Play_FullFood = m_Play.FindAction("FullFood", throwIfNotFound: true);
        m_Play_FullWater = m_Play.FindAction("FullWater", throwIfNotFound: true);
        m_Play_OpenDebugMode = m_Play.FindAction("OpenDebugMode", throwIfNotFound: true);
        // Pause
        m_Pause = asset.FindActionMap("Pause", throwIfNotFound: true);
        m_Pause_SelectLeft = m_Pause.FindAction("SelectLeft", throwIfNotFound: true);
        m_Pause_SelectRight = m_Pause.FindAction("SelectRight", throwIfNotFound: true);
        m_Pause_Enter = m_Pause.FindAction("Enter", throwIfNotFound: true);
        // Result
        m_Result = asset.FindActionMap("Result", throwIfNotFound: true);
        m_Result_BackToTitle = m_Result.FindAction("BackToTitle", throwIfNotFound: true);
        m_Result_SelectLeftOnLevelUp = m_Result.FindAction("SelectLeftOnLevelUp", throwIfNotFound: true);
        m_Result_SelectRightOnLevelUp = m_Result.FindAction("SelectRightOnLevelUp", throwIfNotFound: true);
        m_Result_SelectUpOnEndLevelUp = m_Result.FindAction("SelectUpOnEndLevelUp", throwIfNotFound: true);
        m_Result_SelectDownOnEndLevelUp = m_Result.FindAction("SelectDownOnEndLevelUp", throwIfNotFound: true);
        // Debug
        m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
        m_Debug_DebugMode_Submit = m_Debug.FindAction("DebugMode_Submit", throwIfNotFound: true);
        m_Debug_DebugMode_Cancel = m_Debug.FindAction("DebugMode_Cancel", throwIfNotFound: true);
        m_Debug_DebugMode_Down = m_Debug.FindAction("DebugMode_Down", throwIfNotFound: true);
        m_Debug_DebugMode_Up = m_Debug.FindAction("DebugMode_Up", throwIfNotFound: true);
        m_Debug_DebugMode_Right = m_Debug.FindAction("DebugMode_Right", throwIfNotFound: true);
        m_Debug_DebugMode_Left = m_Debug.FindAction("DebugMode_Left", throwIfNotFound: true);
        // DebugTitle
        m_DebugTitle = asset.FindActionMap("DebugTitle", throwIfNotFound: true);
        m_DebugTitle_Stage1 = m_DebugTitle.FindAction("Stage1", throwIfNotFound: true);
        m_DebugTitle_Stage2 = m_DebugTitle.FindAction("Stage2", throwIfNotFound: true);
        m_DebugTitle_Stage3 = m_DebugTitle.FindAction("Stage3", throwIfNotFound: true);
        m_DebugTitle_Stage4 = m_DebugTitle.FindAction("Stage4", throwIfNotFound: true);
        m_DebugTitle_Stage5 = m_DebugTitle.FindAction("Stage5", throwIfNotFound: true);
        m_DebugTitle_Stage6 = m_DebugTitle.FindAction("Stage6", throwIfNotFound: true);
        m_DebugTitle_Stage7 = m_DebugTitle.FindAction("Stage7", throwIfNotFound: true);
        m_DebugTitle_Stage8 = m_DebugTitle.FindAction("Stage8", throwIfNotFound: true);
        m_DebugTitle_Stage9 = m_DebugTitle.FindAction("Stage9", throwIfNotFound: true);
        m_DebugTitle_Stage10 = m_DebugTitle.FindAction("Stage10", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Title
    private readonly InputActionMap m_Title;
    private ITitleActions m_TitleActionsCallbackInterface;
    private readonly InputAction m_Title_EnterProcess;
    private readonly InputAction m_Title_SelectDown;
    private readonly InputAction m_Title_SelectUp;
    public struct TitleActions
    {
        private @ControlActions m_Wrapper;
        public TitleActions(@ControlActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @EnterProcess => m_Wrapper.m_Title_EnterProcess;
        public InputAction @SelectDown => m_Wrapper.m_Title_SelectDown;
        public InputAction @SelectUp => m_Wrapper.m_Title_SelectUp;
        public InputActionMap Get() { return m_Wrapper.m_Title; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TitleActions set) { return set.Get(); }
        public void SetCallbacks(ITitleActions instance)
        {
            if (m_Wrapper.m_TitleActionsCallbackInterface != null)
            {
                @EnterProcess.started -= m_Wrapper.m_TitleActionsCallbackInterface.OnEnterProcess;
                @EnterProcess.performed -= m_Wrapper.m_TitleActionsCallbackInterface.OnEnterProcess;
                @EnterProcess.canceled -= m_Wrapper.m_TitleActionsCallbackInterface.OnEnterProcess;
                @SelectDown.started -= m_Wrapper.m_TitleActionsCallbackInterface.OnSelectDown;
                @SelectDown.performed -= m_Wrapper.m_TitleActionsCallbackInterface.OnSelectDown;
                @SelectDown.canceled -= m_Wrapper.m_TitleActionsCallbackInterface.OnSelectDown;
                @SelectUp.started -= m_Wrapper.m_TitleActionsCallbackInterface.OnSelectUp;
                @SelectUp.performed -= m_Wrapper.m_TitleActionsCallbackInterface.OnSelectUp;
                @SelectUp.canceled -= m_Wrapper.m_TitleActionsCallbackInterface.OnSelectUp;
            }
            m_Wrapper.m_TitleActionsCallbackInterface = instance;
            if (instance != null)
            {
                @EnterProcess.started += instance.OnEnterProcess;
                @EnterProcess.performed += instance.OnEnterProcess;
                @EnterProcess.canceled += instance.OnEnterProcess;
                @SelectDown.started += instance.OnSelectDown;
                @SelectDown.performed += instance.OnSelectDown;
                @SelectDown.canceled += instance.OnSelectDown;
                @SelectUp.started += instance.OnSelectUp;
                @SelectUp.performed += instance.OnSelectUp;
                @SelectUp.canceled += instance.OnSelectUp;
            }
        }
    }
    public TitleActions @Title => new TitleActions(this);

    // Play
    private readonly InputActionMap m_Play;
    private IPlayActions m_PlayActionsCallbackInterface;
    private readonly InputAction m_Play_Move;
    private readonly InputAction m_Play_Attack;
    private readonly InputAction m_Play_Dash;
    private readonly InputAction m_Play_ChangeWeaponToLeft;
    private readonly InputAction m_Play_ChangeWeaponToRight;
    private readonly InputAction m_Play_AdjustCameraDistance;
    private readonly InputAction m_Play_Resurrection;
    private readonly InputAction m_Play_HighSpeedMove;
    private readonly InputAction m_Play_ToPause;
    private readonly InputAction m_Play_FullHeal;
    private readonly InputAction m_Play_FullFood;
    private readonly InputAction m_Play_FullWater;
    private readonly InputAction m_Play_OpenDebugMode;
    public struct PlayActions
    {
        private @ControlActions m_Wrapper;
        public PlayActions(@ControlActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Play_Move;
        public InputAction @Attack => m_Wrapper.m_Play_Attack;
        public InputAction @Dash => m_Wrapper.m_Play_Dash;
        public InputAction @ChangeWeaponToLeft => m_Wrapper.m_Play_ChangeWeaponToLeft;
        public InputAction @ChangeWeaponToRight => m_Wrapper.m_Play_ChangeWeaponToRight;
        public InputAction @AdjustCameraDistance => m_Wrapper.m_Play_AdjustCameraDistance;
        public InputAction @Resurrection => m_Wrapper.m_Play_Resurrection;
        public InputAction @HighSpeedMove => m_Wrapper.m_Play_HighSpeedMove;
        public InputAction @ToPause => m_Wrapper.m_Play_ToPause;
        public InputAction @FullHeal => m_Wrapper.m_Play_FullHeal;
        public InputAction @FullFood => m_Wrapper.m_Play_FullFood;
        public InputAction @FullWater => m_Wrapper.m_Play_FullWater;
        public InputAction @OpenDebugMode => m_Wrapper.m_Play_OpenDebugMode;
        public InputActionMap Get() { return m_Wrapper.m_Play; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayActions set) { return set.Get(); }
        public void SetCallbacks(IPlayActions instance)
        {
            if (m_Wrapper.m_PlayActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnMove;
                @Attack.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnAttack;
                @Dash.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnDash;
                @Dash.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnDash;
                @Dash.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnDash;
                @ChangeWeaponToLeft.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnChangeWeaponToLeft;
                @ChangeWeaponToLeft.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnChangeWeaponToLeft;
                @ChangeWeaponToLeft.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnChangeWeaponToLeft;
                @ChangeWeaponToRight.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnChangeWeaponToRight;
                @ChangeWeaponToRight.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnChangeWeaponToRight;
                @ChangeWeaponToRight.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnChangeWeaponToRight;
                @AdjustCameraDistance.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnAdjustCameraDistance;
                @AdjustCameraDistance.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnAdjustCameraDistance;
                @AdjustCameraDistance.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnAdjustCameraDistance;
                @Resurrection.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnResurrection;
                @Resurrection.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnResurrection;
                @Resurrection.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnResurrection;
                @HighSpeedMove.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnHighSpeedMove;
                @HighSpeedMove.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnHighSpeedMove;
                @HighSpeedMove.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnHighSpeedMove;
                @ToPause.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnToPause;
                @ToPause.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnToPause;
                @ToPause.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnToPause;
                @FullHeal.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnFullHeal;
                @FullHeal.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnFullHeal;
                @FullHeal.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnFullHeal;
                @FullFood.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnFullFood;
                @FullFood.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnFullFood;
                @FullFood.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnFullFood;
                @FullWater.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnFullWater;
                @FullWater.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnFullWater;
                @FullWater.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnFullWater;
                @OpenDebugMode.started -= m_Wrapper.m_PlayActionsCallbackInterface.OnOpenDebugMode;
                @OpenDebugMode.performed -= m_Wrapper.m_PlayActionsCallbackInterface.OnOpenDebugMode;
                @OpenDebugMode.canceled -= m_Wrapper.m_PlayActionsCallbackInterface.OnOpenDebugMode;
            }
            m_Wrapper.m_PlayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Dash.started += instance.OnDash;
                @Dash.performed += instance.OnDash;
                @Dash.canceled += instance.OnDash;
                @ChangeWeaponToLeft.started += instance.OnChangeWeaponToLeft;
                @ChangeWeaponToLeft.performed += instance.OnChangeWeaponToLeft;
                @ChangeWeaponToLeft.canceled += instance.OnChangeWeaponToLeft;
                @ChangeWeaponToRight.started += instance.OnChangeWeaponToRight;
                @ChangeWeaponToRight.performed += instance.OnChangeWeaponToRight;
                @ChangeWeaponToRight.canceled += instance.OnChangeWeaponToRight;
                @AdjustCameraDistance.started += instance.OnAdjustCameraDistance;
                @AdjustCameraDistance.performed += instance.OnAdjustCameraDistance;
                @AdjustCameraDistance.canceled += instance.OnAdjustCameraDistance;
                @Resurrection.started += instance.OnResurrection;
                @Resurrection.performed += instance.OnResurrection;
                @Resurrection.canceled += instance.OnResurrection;
                @HighSpeedMove.started += instance.OnHighSpeedMove;
                @HighSpeedMove.performed += instance.OnHighSpeedMove;
                @HighSpeedMove.canceled += instance.OnHighSpeedMove;
                @ToPause.started += instance.OnToPause;
                @ToPause.performed += instance.OnToPause;
                @ToPause.canceled += instance.OnToPause;
                @FullHeal.started += instance.OnFullHeal;
                @FullHeal.performed += instance.OnFullHeal;
                @FullHeal.canceled += instance.OnFullHeal;
                @FullFood.started += instance.OnFullFood;
                @FullFood.performed += instance.OnFullFood;
                @FullFood.canceled += instance.OnFullFood;
                @FullWater.started += instance.OnFullWater;
                @FullWater.performed += instance.OnFullWater;
                @FullWater.canceled += instance.OnFullWater;
                @OpenDebugMode.started += instance.OnOpenDebugMode;
                @OpenDebugMode.performed += instance.OnOpenDebugMode;
                @OpenDebugMode.canceled += instance.OnOpenDebugMode;
            }
        }
    }
    public PlayActions @Play => new PlayActions(this);

    // Pause
    private readonly InputActionMap m_Pause;
    private IPauseActions m_PauseActionsCallbackInterface;
    private readonly InputAction m_Pause_SelectLeft;
    private readonly InputAction m_Pause_SelectRight;
    private readonly InputAction m_Pause_Enter;
    public struct PauseActions
    {
        private @ControlActions m_Wrapper;
        public PauseActions(@ControlActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @SelectLeft => m_Wrapper.m_Pause_SelectLeft;
        public InputAction @SelectRight => m_Wrapper.m_Pause_SelectRight;
        public InputAction @Enter => m_Wrapper.m_Pause_Enter;
        public InputActionMap Get() { return m_Wrapper.m_Pause; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PauseActions set) { return set.Get(); }
        public void SetCallbacks(IPauseActions instance)
        {
            if (m_Wrapper.m_PauseActionsCallbackInterface != null)
            {
                @SelectLeft.started -= m_Wrapper.m_PauseActionsCallbackInterface.OnSelectLeft;
                @SelectLeft.performed -= m_Wrapper.m_PauseActionsCallbackInterface.OnSelectLeft;
                @SelectLeft.canceled -= m_Wrapper.m_PauseActionsCallbackInterface.OnSelectLeft;
                @SelectRight.started -= m_Wrapper.m_PauseActionsCallbackInterface.OnSelectRight;
                @SelectRight.performed -= m_Wrapper.m_PauseActionsCallbackInterface.OnSelectRight;
                @SelectRight.canceled -= m_Wrapper.m_PauseActionsCallbackInterface.OnSelectRight;
                @Enter.started -= m_Wrapper.m_PauseActionsCallbackInterface.OnEnter;
                @Enter.performed -= m_Wrapper.m_PauseActionsCallbackInterface.OnEnter;
                @Enter.canceled -= m_Wrapper.m_PauseActionsCallbackInterface.OnEnter;
            }
            m_Wrapper.m_PauseActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SelectLeft.started += instance.OnSelectLeft;
                @SelectLeft.performed += instance.OnSelectLeft;
                @SelectLeft.canceled += instance.OnSelectLeft;
                @SelectRight.started += instance.OnSelectRight;
                @SelectRight.performed += instance.OnSelectRight;
                @SelectRight.canceled += instance.OnSelectRight;
                @Enter.started += instance.OnEnter;
                @Enter.performed += instance.OnEnter;
                @Enter.canceled += instance.OnEnter;
            }
        }
    }
    public PauseActions @Pause => new PauseActions(this);

    // Result
    private readonly InputActionMap m_Result;
    private IResultActions m_ResultActionsCallbackInterface;
    private readonly InputAction m_Result_BackToTitle;
    private readonly InputAction m_Result_SelectLeftOnLevelUp;
    private readonly InputAction m_Result_SelectRightOnLevelUp;
    private readonly InputAction m_Result_SelectUpOnEndLevelUp;
    private readonly InputAction m_Result_SelectDownOnEndLevelUp;
    public struct ResultActions
    {
        private @ControlActions m_Wrapper;
        public ResultActions(@ControlActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @BackToTitle => m_Wrapper.m_Result_BackToTitle;
        public InputAction @SelectLeftOnLevelUp => m_Wrapper.m_Result_SelectLeftOnLevelUp;
        public InputAction @SelectRightOnLevelUp => m_Wrapper.m_Result_SelectRightOnLevelUp;
        public InputAction @SelectUpOnEndLevelUp => m_Wrapper.m_Result_SelectUpOnEndLevelUp;
        public InputAction @SelectDownOnEndLevelUp => m_Wrapper.m_Result_SelectDownOnEndLevelUp;
        public InputActionMap Get() { return m_Wrapper.m_Result; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ResultActions set) { return set.Get(); }
        public void SetCallbacks(IResultActions instance)
        {
            if (m_Wrapper.m_ResultActionsCallbackInterface != null)
            {
                @BackToTitle.started -= m_Wrapper.m_ResultActionsCallbackInterface.OnBackToTitle;
                @BackToTitle.performed -= m_Wrapper.m_ResultActionsCallbackInterface.OnBackToTitle;
                @BackToTitle.canceled -= m_Wrapper.m_ResultActionsCallbackInterface.OnBackToTitle;
                @SelectLeftOnLevelUp.started -= m_Wrapper.m_ResultActionsCallbackInterface.OnSelectLeftOnLevelUp;
                @SelectLeftOnLevelUp.performed -= m_Wrapper.m_ResultActionsCallbackInterface.OnSelectLeftOnLevelUp;
                @SelectLeftOnLevelUp.canceled -= m_Wrapper.m_ResultActionsCallbackInterface.OnSelectLeftOnLevelUp;
                @SelectRightOnLevelUp.started -= m_Wrapper.m_ResultActionsCallbackInterface.OnSelectRightOnLevelUp;
                @SelectRightOnLevelUp.performed -= m_Wrapper.m_ResultActionsCallbackInterface.OnSelectRightOnLevelUp;
                @SelectRightOnLevelUp.canceled -= m_Wrapper.m_ResultActionsCallbackInterface.OnSelectRightOnLevelUp;
                @SelectUpOnEndLevelUp.started -= m_Wrapper.m_ResultActionsCallbackInterface.OnSelectUpOnEndLevelUp;
                @SelectUpOnEndLevelUp.performed -= m_Wrapper.m_ResultActionsCallbackInterface.OnSelectUpOnEndLevelUp;
                @SelectUpOnEndLevelUp.canceled -= m_Wrapper.m_ResultActionsCallbackInterface.OnSelectUpOnEndLevelUp;
                @SelectDownOnEndLevelUp.started -= m_Wrapper.m_ResultActionsCallbackInterface.OnSelectDownOnEndLevelUp;
                @SelectDownOnEndLevelUp.performed -= m_Wrapper.m_ResultActionsCallbackInterface.OnSelectDownOnEndLevelUp;
                @SelectDownOnEndLevelUp.canceled -= m_Wrapper.m_ResultActionsCallbackInterface.OnSelectDownOnEndLevelUp;
            }
            m_Wrapper.m_ResultActionsCallbackInterface = instance;
            if (instance != null)
            {
                @BackToTitle.started += instance.OnBackToTitle;
                @BackToTitle.performed += instance.OnBackToTitle;
                @BackToTitle.canceled += instance.OnBackToTitle;
                @SelectLeftOnLevelUp.started += instance.OnSelectLeftOnLevelUp;
                @SelectLeftOnLevelUp.performed += instance.OnSelectLeftOnLevelUp;
                @SelectLeftOnLevelUp.canceled += instance.OnSelectLeftOnLevelUp;
                @SelectRightOnLevelUp.started += instance.OnSelectRightOnLevelUp;
                @SelectRightOnLevelUp.performed += instance.OnSelectRightOnLevelUp;
                @SelectRightOnLevelUp.canceled += instance.OnSelectRightOnLevelUp;
                @SelectUpOnEndLevelUp.started += instance.OnSelectUpOnEndLevelUp;
                @SelectUpOnEndLevelUp.performed += instance.OnSelectUpOnEndLevelUp;
                @SelectUpOnEndLevelUp.canceled += instance.OnSelectUpOnEndLevelUp;
                @SelectDownOnEndLevelUp.started += instance.OnSelectDownOnEndLevelUp;
                @SelectDownOnEndLevelUp.performed += instance.OnSelectDownOnEndLevelUp;
                @SelectDownOnEndLevelUp.canceled += instance.OnSelectDownOnEndLevelUp;
            }
        }
    }
    public ResultActions @Result => new ResultActions(this);

    // Debug
    private readonly InputActionMap m_Debug;
    private IDebugActions m_DebugActionsCallbackInterface;
    private readonly InputAction m_Debug_DebugMode_Submit;
    private readonly InputAction m_Debug_DebugMode_Cancel;
    private readonly InputAction m_Debug_DebugMode_Down;
    private readonly InputAction m_Debug_DebugMode_Up;
    private readonly InputAction m_Debug_DebugMode_Right;
    private readonly InputAction m_Debug_DebugMode_Left;
    public struct DebugActions
    {
        private @ControlActions m_Wrapper;
        public DebugActions(@ControlActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @DebugMode_Submit => m_Wrapper.m_Debug_DebugMode_Submit;
        public InputAction @DebugMode_Cancel => m_Wrapper.m_Debug_DebugMode_Cancel;
        public InputAction @DebugMode_Down => m_Wrapper.m_Debug_DebugMode_Down;
        public InputAction @DebugMode_Up => m_Wrapper.m_Debug_DebugMode_Up;
        public InputAction @DebugMode_Right => m_Wrapper.m_Debug_DebugMode_Right;
        public InputAction @DebugMode_Left => m_Wrapper.m_Debug_DebugMode_Left;
        public InputActionMap Get() { return m_Wrapper.m_Debug; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
        public void SetCallbacks(IDebugActions instance)
        {
            if (m_Wrapper.m_DebugActionsCallbackInterface != null)
            {
                @DebugMode_Submit.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Submit;
                @DebugMode_Submit.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Submit;
                @DebugMode_Submit.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Submit;
                @DebugMode_Cancel.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Cancel;
                @DebugMode_Cancel.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Cancel;
                @DebugMode_Cancel.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Cancel;
                @DebugMode_Down.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Down;
                @DebugMode_Down.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Down;
                @DebugMode_Down.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Down;
                @DebugMode_Up.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Up;
                @DebugMode_Up.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Up;
                @DebugMode_Up.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Up;
                @DebugMode_Right.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Right;
                @DebugMode_Right.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Right;
                @DebugMode_Right.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Right;
                @DebugMode_Left.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Left;
                @DebugMode_Left.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Left;
                @DebugMode_Left.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnDebugMode_Left;
            }
            m_Wrapper.m_DebugActionsCallbackInterface = instance;
            if (instance != null)
            {
                @DebugMode_Submit.started += instance.OnDebugMode_Submit;
                @DebugMode_Submit.performed += instance.OnDebugMode_Submit;
                @DebugMode_Submit.canceled += instance.OnDebugMode_Submit;
                @DebugMode_Cancel.started += instance.OnDebugMode_Cancel;
                @DebugMode_Cancel.performed += instance.OnDebugMode_Cancel;
                @DebugMode_Cancel.canceled += instance.OnDebugMode_Cancel;
                @DebugMode_Down.started += instance.OnDebugMode_Down;
                @DebugMode_Down.performed += instance.OnDebugMode_Down;
                @DebugMode_Down.canceled += instance.OnDebugMode_Down;
                @DebugMode_Up.started += instance.OnDebugMode_Up;
                @DebugMode_Up.performed += instance.OnDebugMode_Up;
                @DebugMode_Up.canceled += instance.OnDebugMode_Up;
                @DebugMode_Right.started += instance.OnDebugMode_Right;
                @DebugMode_Right.performed += instance.OnDebugMode_Right;
                @DebugMode_Right.canceled += instance.OnDebugMode_Right;
                @DebugMode_Left.started += instance.OnDebugMode_Left;
                @DebugMode_Left.performed += instance.OnDebugMode_Left;
                @DebugMode_Left.canceled += instance.OnDebugMode_Left;
            }
        }
    }
    public DebugActions @Debug => new DebugActions(this);

    // DebugTitle
    private readonly InputActionMap m_DebugTitle;
    private IDebugTitleActions m_DebugTitleActionsCallbackInterface;
    private readonly InputAction m_DebugTitle_Stage1;
    private readonly InputAction m_DebugTitle_Stage2;
    private readonly InputAction m_DebugTitle_Stage3;
    private readonly InputAction m_DebugTitle_Stage4;
    private readonly InputAction m_DebugTitle_Stage5;
    private readonly InputAction m_DebugTitle_Stage6;
    private readonly InputAction m_DebugTitle_Stage7;
    private readonly InputAction m_DebugTitle_Stage8;
    private readonly InputAction m_DebugTitle_Stage9;
    private readonly InputAction m_DebugTitle_Stage10;
    public struct DebugTitleActions
    {
        private @ControlActions m_Wrapper;
        public DebugTitleActions(@ControlActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Stage1 => m_Wrapper.m_DebugTitle_Stage1;
        public InputAction @Stage2 => m_Wrapper.m_DebugTitle_Stage2;
        public InputAction @Stage3 => m_Wrapper.m_DebugTitle_Stage3;
        public InputAction @Stage4 => m_Wrapper.m_DebugTitle_Stage4;
        public InputAction @Stage5 => m_Wrapper.m_DebugTitle_Stage5;
        public InputAction @Stage6 => m_Wrapper.m_DebugTitle_Stage6;
        public InputAction @Stage7 => m_Wrapper.m_DebugTitle_Stage7;
        public InputAction @Stage8 => m_Wrapper.m_DebugTitle_Stage8;
        public InputAction @Stage9 => m_Wrapper.m_DebugTitle_Stage9;
        public InputAction @Stage10 => m_Wrapper.m_DebugTitle_Stage10;
        public InputActionMap Get() { return m_Wrapper.m_DebugTitle; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugTitleActions set) { return set.Get(); }
        public void SetCallbacks(IDebugTitleActions instance)
        {
            if (m_Wrapper.m_DebugTitleActionsCallbackInterface != null)
            {
                @Stage1.started -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage1;
                @Stage1.performed -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage1;
                @Stage1.canceled -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage1;
                @Stage2.started -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage2;
                @Stage2.performed -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage2;
                @Stage2.canceled -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage2;
                @Stage3.started -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage3;
                @Stage3.performed -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage3;
                @Stage3.canceled -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage3;
                @Stage4.started -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage4;
                @Stage4.performed -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage4;
                @Stage4.canceled -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage4;
                @Stage5.started -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage5;
                @Stage5.performed -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage5;
                @Stage5.canceled -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage5;
                @Stage6.started -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage6;
                @Stage6.performed -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage6;
                @Stage6.canceled -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage6;
                @Stage7.started -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage7;
                @Stage7.performed -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage7;
                @Stage7.canceled -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage7;
                @Stage8.started -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage8;
                @Stage8.performed -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage8;
                @Stage8.canceled -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage8;
                @Stage9.started -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage9;
                @Stage9.performed -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage9;
                @Stage9.canceled -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage9;
                @Stage10.started -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage10;
                @Stage10.performed -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage10;
                @Stage10.canceled -= m_Wrapper.m_DebugTitleActionsCallbackInterface.OnStage10;
            }
            m_Wrapper.m_DebugTitleActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Stage1.started += instance.OnStage1;
                @Stage1.performed += instance.OnStage1;
                @Stage1.canceled += instance.OnStage1;
                @Stage2.started += instance.OnStage2;
                @Stage2.performed += instance.OnStage2;
                @Stage2.canceled += instance.OnStage2;
                @Stage3.started += instance.OnStage3;
                @Stage3.performed += instance.OnStage3;
                @Stage3.canceled += instance.OnStage3;
                @Stage4.started += instance.OnStage4;
                @Stage4.performed += instance.OnStage4;
                @Stage4.canceled += instance.OnStage4;
                @Stage5.started += instance.OnStage5;
                @Stage5.performed += instance.OnStage5;
                @Stage5.canceled += instance.OnStage5;
                @Stage6.started += instance.OnStage6;
                @Stage6.performed += instance.OnStage6;
                @Stage6.canceled += instance.OnStage6;
                @Stage7.started += instance.OnStage7;
                @Stage7.performed += instance.OnStage7;
                @Stage7.canceled += instance.OnStage7;
                @Stage8.started += instance.OnStage8;
                @Stage8.performed += instance.OnStage8;
                @Stage8.canceled += instance.OnStage8;
                @Stage9.started += instance.OnStage9;
                @Stage9.performed += instance.OnStage9;
                @Stage9.canceled += instance.OnStage9;
                @Stage10.started += instance.OnStage10;
                @Stage10.performed += instance.OnStage10;
                @Stage10.canceled += instance.OnStage10;
            }
        }
    }
    public DebugTitleActions @DebugTitle => new DebugTitleActions(this);
    public interface ITitleActions
    {
        void OnEnterProcess(InputAction.CallbackContext context);
        void OnSelectDown(InputAction.CallbackContext context);
        void OnSelectUp(InputAction.CallbackContext context);
    }
    public interface IPlayActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnChangeWeaponToLeft(InputAction.CallbackContext context);
        void OnChangeWeaponToRight(InputAction.CallbackContext context);
        void OnAdjustCameraDistance(InputAction.CallbackContext context);
        void OnResurrection(InputAction.CallbackContext context);
        void OnHighSpeedMove(InputAction.CallbackContext context);
        void OnToPause(InputAction.CallbackContext context);
        void OnFullHeal(InputAction.CallbackContext context);
        void OnFullFood(InputAction.CallbackContext context);
        void OnFullWater(InputAction.CallbackContext context);
        void OnOpenDebugMode(InputAction.CallbackContext context);
    }
    public interface IPauseActions
    {
        void OnSelectLeft(InputAction.CallbackContext context);
        void OnSelectRight(InputAction.CallbackContext context);
        void OnEnter(InputAction.CallbackContext context);
    }
    public interface IResultActions
    {
        void OnBackToTitle(InputAction.CallbackContext context);
        void OnSelectLeftOnLevelUp(InputAction.CallbackContext context);
        void OnSelectRightOnLevelUp(InputAction.CallbackContext context);
        void OnSelectUpOnEndLevelUp(InputAction.CallbackContext context);
        void OnSelectDownOnEndLevelUp(InputAction.CallbackContext context);
    }
    public interface IDebugActions
    {
        void OnDebugMode_Submit(InputAction.CallbackContext context);
        void OnDebugMode_Cancel(InputAction.CallbackContext context);
        void OnDebugMode_Down(InputAction.CallbackContext context);
        void OnDebugMode_Up(InputAction.CallbackContext context);
        void OnDebugMode_Right(InputAction.CallbackContext context);
        void OnDebugMode_Left(InputAction.CallbackContext context);
    }
    public interface IDebugTitleActions
    {
        void OnStage1(InputAction.CallbackContext context);
        void OnStage2(InputAction.CallbackContext context);
        void OnStage3(InputAction.CallbackContext context);
        void OnStage4(InputAction.CallbackContext context);
        void OnStage5(InputAction.CallbackContext context);
        void OnStage6(InputAction.CallbackContext context);
        void OnStage7(InputAction.CallbackContext context);
        void OnStage8(InputAction.CallbackContext context);
        void OnStage9(InputAction.CallbackContext context);
        void OnStage10(InputAction.CallbackContext context);
    }
}
